---
title: "Report: Australian Census Data"
subtitle: "ETC5513 Assignment 4: Star Wars"
author:
- familyname: Faizan
  othernames: Mohammed
  address: Monash University
  email: mfai0014@student.monash.edu
  correspondingauthor: true
  qualifications:  MBAt
- familyname: More
  othernames: Adarsh
  address: Monash University
  email: amor0060@student.monash.edu
  qualifications: MBAt
- familyname: LI
  othernames: Yanhui
  address: Monash University
  email: yli807@student.monash.edu
  correspondingauthor: true
  qualifications:  MBAt
department: Our consultancy - Star Wars\newline Mohammed Faizan &\newline Adarsh More&\newline Yanhui LI
organization: Monash University
bibliography: 
- references.bib
- packages.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::html_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
keep_md: true
---

```{r echo=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path = "Figures/", fig.align ="center",
                      out.width = "50%", echo = FALSE, 
                      messages = FALSE, 
                      warning = FALSE)

# Loading Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(tinytex)
library(bookdown)
library(naniar)
library(visdat)
library(citation)
library(knitr)
library(scales)
library(patchwork)
library(sf)
library(glue)
library(unglue)
library(sugarbag)
library(readxl)
library(tidytext)
library(rpart)
library(rpart.plot)
library(broomstick)
library(plotly)
library(igraph)
library(ggraph)
```


```{r writing_packages_bibliographies}
knitr::write_bib(c(.packages()), "packages.bib")
```

```{r}
celldiscriptors <- read_excel(here::here("data/australian_census_data_2016/Metadata/Metadata_2016_GCP_DataPack.xlsx"), sheet=2, skip=10)
```


```{r}
data_path <- here::here("data/australian_census_data_2016/")

census_paths <- glue::glue(data_path, "2016 Census GCP All Geographies for VIC/SA4/VIC/2016Census_G{number}{alpha}_VIC_SA4.csv", 
                         number = c("46","46","47","47","47","51","51","51","51","57","57"), alpha = c("A","B","A","B","C","A","B","C","D","A","B"))
```
```{r geopath, include=FALSE}
geopath <- glue::glue(data_path, "2016_SA4_shape/SA4_2016_AUST.shp")

sa4_codes<- read_csv(census_paths[2]) %>% 
                mutate(SA4_CODE_2016 = as.character(SA4_CODE_2016)) %>% 
                select(SA4_CODE_2016)


sa4_geomap <- read_sf(geopath) %>%
  right_join(sa4_codes, by=c("SA4_CODE16" = "SA4_CODE_2016"))


```

```{r}
ggplot(sa4_geomap) +
  geom_sf()
```


```{r}
g51 <- map_dfr(census_paths[6:8], ~{
  df <- read_csv(.x) %>%
      select(-starts_with("P"), -contains("Tot")) %>%
            mutate(SA4_CODE_2016 = as.character(SA4_CODE_2016)) %>% 
  pivot_longer(cols = -c(SA4_CODE_2016),
                  names_to = "category",
                  values_to = "count") %>%
  unglue_unnest(category, 
                    c("{sex=[MF]}_{industry=(Ag_For_Fshg|Mining|Manufact|El_Gas_Wt_Waste|Constru|WhlesaleTde|RetTde|Accom_food|Trans_post_wrehsg|Info_media_teleco|Fin_Insur|RtnHir_REst|Pro_scien_tec|Admin_supp|Public_admin_sfty|Educ_trng|HlthCare_SocAs|Art_recn|Oth_scs|ID_NS)}_{age_min=\\d+}_{age_max=\\d+}",
                      "{sex=[MF]}_{industry=(Ag_For_Fshg|Mining|Manufact|El_Gas_Wt_Waste|Constru|WhlesaleTde|RetTde|Accom_food|Trans_post_wrehsg|Info_media_teleco|Fin_Insur|RtnHir_REst|Pro_scien_tec|Admin_supp|Public_admin_sfty|Educ_trng|HlthCare_SocAs|Art_recn|Oth_scs|ID_NS)}_{age_min=\\d+}ov"
                     ),
                remove = FALSE)
})


```
```{r}
g51 <- g51 %>% 
  mutate(industry =case_when(
                            str_detect(industry, "Ag_For_Fshg") ~ "Agriculture_forestry_and_fishing",
                            str_detect(industry, "Manufact") ~ "Manufacturing",
                            str_detect(industry, "El_Gas_Wt_Waste") ~ "Electricity_gas_water_and_waste_service",
                            str_detect(industry, "Constru") ~ "Construction",
                            str_detect(industry, "Ag_Envir_Rltd_Sts") ~ "Agriculture_Environment",
                            str_detect(industry, "WhlesaleTde") ~ "Wholesale_trade",
                            str_detect(industry, "RetTde") ~ "Retail_trade",
                            str_detect(industry, "Accom_food") ~ "Accommodation_and_food_services",
                            str_detect(industry, "Trans_post_wrehsg") ~ "Transport_postal_and_warehousing",
                            str_detect(industry, "Info_media_teleco") ~ "Information_media_and_telecommunications",
                            str_detect(industry, "Fin_Insur") ~ "Financial_and_insurance_services",
                            str_detect(industry, "RtnHir_REst") ~ "Rental_hiring_and_real_estate_services",
                            str_detect(industry, "Pro_scien_tec") ~ "Professional_scientific_and_technical_services",
                            str_detect(industry, "Admin_supp") ~ "Administrative_and_support_services",
                            str_detect(industry, "Public_admin_sfty") ~ "Public_administration_and_safety",
                            str_detect(industry, "Educ_trng") ~ "Education_and_training",
                            str_detect(industry, "HlthCare_SocAs") ~ "Health_care_and_social_assistance",
                            str_detect(industry, "Art_recn") ~ "Arts_and_recreation_services",
                            str_detect(industry, "Oth_scs") ~ "Other_services",
                            str_detect(industry, "ID_NS") ~ "Not Stated",
                            TRUE ~ industry))  %>%
  select(-category) %>%
  rename(count_industry = count)


```
```{r}
g57 <- map_dfr(census_paths[10], ~{
  df <- read_csv(.x) %>%
      select(-starts_with("P"), -contains("Tot")) %>%
            mutate(SA4_CODE_2016 = as.character(SA4_CODE_2016)) %>% 
  pivot_longer(cols = -c(SA4_CODE_2016),
                  names_to = "category",
                  values_to = "count") %>%
  unglue_unnest(category, 
                    c("{sex=[MF]}{age_min=\\d+}_{age_max=\\d+}_{occupation=(Managers|Professionals|TechnicTrades_Wrs|CommunPersnlSvc_W|ClericalAdminis_W|Sales_W|Mach_oper_drivers|Labourers|Occu_ID_NS|TechnicTrades_W)}",
                      "{sex=[MF]}{age_min=\\d+}ov_{occupation=(Managers|Professionals|TechnicTrades_Wrs|CommunPersnlSvc_W|ClericalAdminis_W|Sales_W|Mach_oper_drivers|Labourers|Occu_ID_NS|TechnicTrades_W)}",
                      "{sex=[MF]}{age_min=\\d+}_ov_{occupation=(Managers|Professionals|TechnicTrades_Wrs|CommunPersnlSvc_W|ClericalAdminis_W|Sales_W|Mach_oper_drivers|Labourers|Occu_ID_NS|TechnicTrades_W)}"
                      ),  
                remove = FALSE)  
})

```
```{r}
g57 <- g57 %>% 
  mutate(occupation =case_when(
                            str_detect(occupation, "TechnicTrades_W") ~ "Technicians_and_trades_workers",
                            str_detect(occupation, "TechnicTrades_Wrs") ~ "Technicians_and_trades_workers",
                            str_detect(occupation, "CommunPersnlSvc") ~ "Community_and_personal_service_workers",
                            str_detect(occupation, "ClericalAdminis_W") ~ "Clerical_and_administrative_workers",
                            str_detect(occupation, "Sales_W") ~ "Sales_workers",
                            str_detect(occupation, "Mach_oper_drivers") ~ "Machinery_operators_and_drivers",
                            str_detect(occupation, "Occu_ID_NS") ~ "Not Stated",
                            TRUE ~ occupation))  %>%
  select(-category) %>%
  rename(count_occupation = count)

```

```{r cases-distribution, message=FALSE,warning=FALSE}
g51 %>% 
  group_by(industry) %>% 
  ggplot() +
  geom_histogram(mapping = aes(x = count_industry)) +
  labs(title = "Population Distribution by Industry of Employment", x = "Number of Industries", y = "Count")

#4000 records with near to 500 count_industry values.
```



```{r , fig.cap=""}
g51 %>%
  ggplot(mapping = aes(x = fct_reorder(industry,count_industry), y = count_industry, fill = sex)) +
  geom_col(mapping = aes(x = reorder(industry,count_industry), y = count_industry, fill = sex)) +
  labs(title = "Population Share of Industries", y = "Number of Employees") +
  scale_y_continuous(label=label_number()) +
  coord_flip() 

g51 %>%
  ggplot(mapping = aes(x = fct_reorder(industry,count_industry), y = count_industry, fill = sex)) +
  geom_col(mapping = aes(x = reorder_within(industry,count_industry, sex), y = count_industry, fill = sex)) +
  labs(title = "Population Share of Industries", y = "Number of Employees") +
  scale_y_continuous(label=label_number()) +
  coord_flip() 

```
```{r}
vicpopulation <- g51 %>%
  group_by(SA4_CODE_2016) %>%
  summarise(population = sum(count_industry))

vicpopulation <- g51 %>%
  group_by(SA4_CODE_2016, sex) %>%
  summarise(population = sum(count_industry)) %>%
  ungroup(sex) %>%
  pivot_wider(names_from = sex,
              values_from = population) %>%
  rename(malepopulation = M,
         femalepopulation = `F`) %>%
  full_join(vicpopulation)

```
```{r}
vicpopulation %>% 
  full_join(sa4_geomap, 
            by = c("SA4_CODE_2016"="SA4_CODE")) %>%
  ggplot() +
  geom_sf(mapping = aes(geometry= geometry, fill=population)) +
  geom_sf_text(aes(geometry= geometry,label=SA4_CODE_2016, colour="white"), 
               check_overlap=TRUE)+
  theme_void() 
```
```{r}
g51 %>%
  pivot_wider(names_from = sex,
              values_from = count_industry) %>%
  ggplot(mapping = aes(x = M, y = `F`, colour = industry)) +
  geom_point() +
  labs(title = "Population: Male vs Female", 
       x = "Male Population",
       y= "Female Population") +
  scale_y_continuous(label=label_number()) +
  scale_x_continuous(label=label_number()) +
  theme(legend.position = "bottom")
```
```{r}
g51indmfnest <- g51 %>%
  pivot_wider(names_from = sex,
              values_from = count_industry) %>%
  select(industry, `F`, M ) %>%
  group_by(industry) %>%
  nest() %>%
  mutate(model = map(data, lm)) %>%
  mutate(aug = map(model, broomstick::augment)) %>%
  unnest(aug)

mvf <- ggplot(g51indmfnest,
       aes(x = M)) +
# index represent splitting value,
#geom_point(aes(y = `F`, colour = industry, aplha=0)) +
geom_line(aes(y = .fitted, colour = industry)) +
  theme(legend.position = "bottom")  +
  labs(title = "Population: Male vs Female", 
       x = "Male Population",
       y= "Female Population")
  # geom_text(aes(y = .fitted,label=industry, colour="white"), 
  #              check_overlap=TRUE)

ggplotly(mvf) %>%
  hide_legend()
```

```{r}
g51redundantage <-  g51[rep(rownames(g51), g51$count_industry), ]


ageindcount <- g51redundantage %>%
  ggplot(mapping = aes(x = age_min, y = industry)) +
  geom_count() +
  labs(title = "Population: Industries and Age", x = "Age") +
  theme(axis.title.y = element_blank())

ggplotly(ageindcount)
```
```{r agedistribution}
g51redundantage %>%
  ggplot()+
  geom_density(mapping = aes( x = as.numeric(age_min),
                              colour = sex, 
                              alpha = 0.5)) +
  scale_x_continuous()
```

```{r}
popindage <- g51 %>%
  group_by(industry, age_min) %>%
  summarise(count_indage = sum(count_industry)) %>%
  ungroup()

nodes <- data.frame(node = unique(popindage$industry),
                    category = "industry") %>%
  full_join(data.frame(node = unique(popindage$age_min),
                    category = "age"))

popindage <- popindage[,c(1,2,3,1)]


networkindage <-   graph_from_data_frame(d=popindage,directed = TRUE, vertices = nodes)


a <- grid::arrow(type = "closed", length = unit(0.2,"inches"))
set.seed(122)
networkindage %>%
  ggraph(layout = "stress") +
  geom_edge_link2(aes(edge_alpha = count_indage,edge_width = count_indage,edge_color = industry),arrow = a) +
  geom_node_point(aes(size = 2, colour =category) )+
  geom_node_text(aes(label = name), repel = TRUE,  point.padding = unit(0.15, "lines")) +
theme_void() +
  theme(legend.position = "none")

```


```{r }
popindarea <- g51 %>%
  group_by(SA4_CODE_2016, industry) %>%
  summarise(count_indarea = sum(count_industry)) %>%
  ungroup()

nodesarea <- data.frame(node = unique(popindarea$SA4_CODE_2016),
                    category = "area") %>%
  full_join(data.frame(node = unique(popindarea$industry),
                    category = "industry"))

popindarea <- popindarea[,c(1,2,3,2)]


networkindarea <-   graph_from_data_frame(d=popindarea,directed = TRUE, vertices = nodesarea)


a <- grid::arrow(type = "closed", length = unit(0.2,"inches"))
networkindarea %>%
  ggraph(layout = "stress") +
  geom_edge_link2(aes(edge_alpha = count_indarea,edge_width = count_indarea,edge_color = industry),arrow = a) +
  geom_node_point(aes(size = 2, colour =category) )+
  geom_node_text(aes(label = name), repel = TRUE,  point.padding = unit(0.15, "lines")) +
theme_void() +
  theme(legend.position = "none")

```

```{r popindarea, fig.cap="Spatial Industry Distribution"}

popindareamax <- popindarea %>% 
  select(1:3) %>%
  group_by(SA4_CODE_2016) %>%
  slice_max(count_indarea)

popindareamax %>% 
  full_join(sa4_geomap, 
            by = c("SA4_CODE_2016"="SA4_CODE")) %>%
  ggplot() +
  geom_sf(mapping = aes(geometry= geometry, fill=industry)) +
 # geom_sf_text(aes(geometry= geometry,label=industry, colour="white"), check_overlap=TRUE)+
  theme_void() +
  theme(legend.position = "bottom")

#major industry in cbd is helthcare
#major industry in country side is agriculture
```

```{r popareaind, fig.cap=""}

popareaindmax <- popindarea %>% 
  select(1:3) %>%
  group_by(industry) %>%
  slice_max(count_indarea) %>%
  arrange(SA4_CODE_2016)

popareaindmax %>% 
  full_join(sa4_geomap, 
            by = c("SA4_CODE_2016"="SA4_CODE")) %>%
  ggplot() +
  geom_sf(mapping = aes(geometry= geometry, fill=industry)) +
  geom_sf_text(aes(geometry= geometry,label=industry, colour="white"), check_overlap=TRUE)+
  theme_void() +
  theme(legend.position = "none")

popareaindmax %>%
  ggplot(mapping = aes(x = fct_reorder(industry,count_industry), y = count_industry, fill = sex)) +
  geom_col(mapping = aes(x = reorder_within(industry,count_indarea, SA4_CODE_2016), y = count_indarea, fill = industry)) +
  labs(title = "Region and Best Industry", y = "Number of Employees") +
  scale_y_continuous(label=label_number()) +
  coord_flip()  +
  theme(legend.position = "none")

```

