---
title: "Report: Australian Census Data"
subtitle: "ETC5513 Assignment 4: Star Wars"
author:
- familyname: Faizan
  othernames: Mohammed
  address: Monash University
  email: mfai0014@student.monash.edu
  correspondingauthor: true
  qualifications:  MBAt
- familyname: More
  othernames: Adarsh
  address: Monash University
  email: amor0060@student.monash.edu
  qualifications: MBAt
- familyname: LI
  othernames: Yanhui
  address: Monash University
  email: yli807@student.monash.edu
  correspondingauthor: true
  qualifications:  MBAt
department: Our consultancy - Star Wars\newline Mohammed Faizan &\newline Adarsh More&\newline Yanhui LI
organization: Monash University
bibliography: 
- references.bib
- packages.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::html_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
keep_md: true
always_allow_html: true
---

```{r echo=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.path = "Figures/", fig.align ="center",
                      out.width = "50%", echo = FALSE, 
                      messages = FALSE, 
                      warning = FALSE)
# Loading Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(tinytex)
library(bookdown)
library(naniar)
library(visdat)
library(citation)
library(knitr)
library(scales)
library(patchwork)
library(sf)
library(glue)
library(unglue)
library(sugarbag)
library(readxl)
library(plotly)
library(tidytext)
library(ggplot2)
library(igraph)
library(ggraph)
```

```{r}
vpsc_data <- here::here("data/vpsc_data/")
```

```{r}
employer <- read.csv(glue::glue(vpsc_data, "data-1h4Zk.csv"))
```

```{r}
work_location <- read_excel(glue::glue(vpsc_data, "Work-location.xlsx"),skip=1) %>%
  mutate(across(starts_with("June"), as.numeric)) 

```

```{r}
salary_occ <- read_excel(glue::glue(vpsc_data, "Remuneration.xlsx"),skip=1,sheet=2) %>%
  mutate(across(starts_with("June"), as.integer)) %>%
  filter(!str_detect(Group,"^ For executives, Total Remuneration Package (TRP),  inclusive of salary, superannuation and packaged benefits is used.
N"))
```
```{r}
salary_ind <- read_xlsx(glue::glue(vpsc_data, "Remuneration.xlsx"),skip=1,sheet=1, col_types="text",guess_max=11) %>%
  mutate(across(starts_with("June"), as.integer)) %>%
  filter(str_detect(Measure, "Non-casual employees|Median full time equivalent base"))
```

```{r}
employment_number_ind <- read_excel(glue::glue(vpsc_data, "Employment-numbers-over-time.xlsx"),skip=1,sheet=1) 
  
```
```{r}
employment_number_occ <- read_excel(glue::glue(vpsc_data, "Employment-numbers-over-time.xlsx"),skip=1,sheet=2) 
```

```{r}
employment_type <- read_excel(glue::glue(vpsc_data, "Employment-status-ongoing-fixed-term-and-casual-employment.xlsx"),skip=1,sheet=1,na="-")  %>%
    mutate(across(starts_with("June"), as.numeric)) 

```

```{r}
employer %>%
  ggplot()+
  geom_col(aes(x=Type, y=Headcount))+
  theme(axis.text.x = element_text(angle = 45))
```
```{r}
employment_number_ind %>% 
  pivot_longer(cols = -c(`Industry sector`,Group,Measure),
               names_to = "year",
               values_to = "Headcount") %>%
  filter(Group=="All employees" & Measure=="Headcount") %>%
  ggplot()+
  geom_col(aes(x=`Industry sector`, y=`Headcount`))+
  facet_wrap(~year, ncol=2) +
  theme(axis.text.x = element_text(angle = 45))
```
```{r}
employment_number_ind %>% 
  pivot_longer(cols = -c(`Industry sector`,Group,Measure),
               names_to = "year",
               values_to = "Headcount") %>%
  filter(Group %in% c("Man","Woman") & Measure=="Headcount") %>%
  ggplot()+
  geom_col(aes(x=`Industry sector`, y=`Headcount`))+
  facet_wrap(~Group) +
  theme(axis.text.x = element_text(angle = 45))
```
```{r}
employment_number_occ %>% 
  pivot_longer(cols = -c(`Occupation`,Gender,Measure),
               names_to = "year",
               values_to = "Headcount") %>%
  filter(Gender %in% c("Man","Woman") & Measure=="Headcount") %>%
  ggplot()+
  geom_col(aes(x=`Occupation`, y=`Headcount`))+
  facet_wrap(~Gender) +
  theme(axis.text.x = element_text(angle = 45))
```

```{r}
salary_occ %>%
  ggplot()+
  geom_col(aes(x=reorder(`Occupation`,`June 2016`) , y=`June 2016`))+
  theme(axis.text.x = element_text(angle = 45), axis.title.y = element_blank())+
  facet_wrap(~Group) +
  coord_flip()
```
```{r}
salary_ind %>%
  filter(str_detect(Group, "Man|Woman")) %>%
  ggplot()+
  geom_col(aes(x=reorder(`Industry sector`,`June 2016`) , y=`June 2016`))+
  theme(axis.text.x = element_text(angle = 45), axis.title.y = element_blank())+
  facet_wrap(~Group) +
  coord_flip()
```
